export const HINDI_LABELS = {
  new_request: 'नया अनुरोध',
  assigned: 'सौंपा गया',
  in_progress: 'प्रगति में',
  resolved: 'समाधान हुआ',
  rejected: 'अस्वीकार किया गया',
  escalated: 'आगे बढ़ाया गया',
  low: 'निम्न',
  medium: 'मध्यम',
  high: 'उच्च',
  critical: 'गंभीर',
  draft: 'ड्राफ्ट',
  scheduled: 'निर्धारित',
  active: 'सक्रिय',
  completed: 'पूर्ण',
  pending: 'लंबित',
  published: 'प्रकाशित',
  supporter: 'समर्थक',
  neutral: 'तटस्थ',
  opposition: 'विपक्षी',
  unknown_support: 'अज्ञात',
  male: 'पुरुष',
  female: 'महिला',
  other: 'अन्य',
  unknown: 'अज्ञात',
  rural: 'ग्रामीण',
  urban: 'शहरी',
  water: 'पानी',
  electricity: 'बिजली',
  road: 'सड़क',
  hospital: 'अस्पताल',
  police: 'पुलिस',
  pension: 'पेंशन',
  government_scheme: 'सरकारी योजना',
  education: 'शिक्षा',
  sanitation: 'स्वच्छता',
  corruption: 'भ्रष्टाचार',
  emergency: 'आपातकालीन',
  super_admin: 'सुपर एडमिन',
  admin: 'एडमिन',
  sub_admin: 'उप एडमिन',
  district_manager: 'जिला प्रबंधक',
  area_manager: 'क्षेत्र प्रबंधक',
  field_worker: 'फील्ड कार्यकर्ता',
  volunteer: 'स्वयंसेवक',
  pr_team: 'पीआर टीम',
  data_entry_operator: 'डेटा एंट्री ऑपरेटर',
  complaint_manager: 'अनुरोध प्रबंधक',
  campaign_manager: 'अभियान प्रबंधक',
  public_user: 'जन उपयोगकर्ता',
  manage_population: 'जनसंख्या प्रबंधन',
  manage_campaigns: 'अभियान प्रबंधन',
  manage_requests: 'अनुरोध प्रबंधन',
  manage_users: 'उपयोगकर्ता प्रबंधन',
  manage_roles: 'भूमिका प्रबंधन',
  manage_pr: 'पीआर प्रबंधन',
  manage_areas: 'क्षेत्र प्रबंधन',
  manage_work: 'कार्य प्रबंधन',
  view_analytics: 'रिपोर्ट देखें',
  submit_requests: 'अनुरोध दर्ज करें',
  image_url: 'छवि',
  title: 'शीर्षक',
  language: 'भाषा',
  campaign_status: 'अभियान स्थिति',
  target_support_status: 'समर्थन स्थिति',
  target_area: 'लक्षित क्षेत्र',
  target_village: 'लक्षित गांव',
  scheduled_at: 'निर्धारित दिनांक',
  published_at: 'प्रकाशन दिनांक',
  content: 'सामग्री',
  status: 'स्थिति',
  name: 'नाम',
  mobile_number: 'मोबाइल नंबर',
  phone_number: 'मोबाइल नंबर',
  role: 'भूमिका',
  area: 'क्षेत्र',
  village: 'गांव',
  ward: 'वार्ड',
  village_or_ward: 'गांव / वार्ड',
  political_support_status: 'राजनीतिक समर्थन',
  work_type: 'कार्य प्रकार',
  assigned_to: 'कार्यकर्ता',
}

export function humanizeEnum(value) {
  if (value == null || value === '') return ''
  return HINDI_LABELS[value] || String(value)
}

export function optionLabel(value) {
  return humanizeEnum(value)
}
